### PR TITLE
Bugfix: SPDD errors in Main (started from genesis) fixed

### LINKED ISSUE #882: Bugs in SPDD in epochs 2xx (Mainnet, processed from genesis)
After merge with PR829, changes in protocol parameters processing (in account_state module) for Conway affected processing of Shelley. The bugs should be fixed.

More detail:
* Conway requires an epoch between votes epoch and enactment epoch for a governance action:
Vote|----|Enactment
* Shelley can do it quicker:
Vote|Enactment

However, account_state module computes rewards in uniform fashion. Therefore, specific delay should be implemented, which properly handles all eras.

### PR DESCRIPTION
**Pull request by shd**
## Description

After merge with PR829, changes in protocol parameters processing (in account_state module) for Conway affected processing of Shelley. This PR fixes those bugs.

## Related Issue(s)
Fixes #882 

## How was this tested?
- unit tests (standard)
- integration tests (running from genesis, running from snapshot, making sure that there are no SPDD errors in logs)

## Checklist

- [x] My code builds and passes local tests
- [x] I added/updated tests for my changes, where applicable
- [x] I updated documentation (if applicable)
- [x] branch has ≤ 5 commits (honor system)
- [x] commit messages tell a coherent story
- [x] branch is up to date with main (rebased on main; fast-forward possible)
- [x] CI/CD passes on the merged-with-main result

## Impact / Side effects
May affect rewards, treasury calculations; further testing is needed after this PR.

### CODE REVIEW

File: modules/accounts_state/src/state.rs [hunk 1]
```diff
@@ -82,6 +82,20 @@ pub struct PendingRewardsPlan {
...
 }
 
+#[derive(Clone, Debug, Default)]
+pub struct ProtocolParametersState {
+    /// Initialized when parameters are updated, contains number of the
+    /// epoch being started.
+    current_epoch: u64,
+
+    /// Protocol parameters (used for account calculations in current epoch).
+    current: Arc<ProtocolParams>,
```
Comment (whankinsiv) [inline modules/accounts_state/src/state.rs]: Could you remove these Arcs? We won't rollback properly with them.

**Review by whankinsiv — APPROVED** [review]
Nice work!
