### PR TITLE
fix: spdd and rewards for Conway era bootstrapping

### LINKED ISSUE #574: Rewards calculation and SPDD verification mismatches from epoch 508 onwards
Part of #220

## Context

The accounts_state module calculates rewards at epoch boundaries and verifies them against reference data from the Haskell node (via DBSync). When bootstrapping from a snapshot at epoch 507 and transitioning through subsequent epochs, several verification mismatches occur in treasury, reserves, deposits, and stake pool distribution data (SPDD).

## Problem

Multiple verification errors occur during epoch transitions, indicating discrepancies between our calculated values and the reference Cardano node:

### Treasury/Reserves/Deposits Mismatches

```
ERROR: Verification mismatch: treasury for epoch=511 calculated=1546538247841511 desired=1546537960700287 difference=-287141224
ERROR: Verification mismatch: deposits for epoch=511 calculated=4473496000000 desired=4373496000000 difference=-100000000000
```

### SPDD (Stake Pool Distribution Data) Mismatches

```
ERROR: SPDD verification epoch 511 total active stake difference: reference 22686595602651204 != computed 22686595559055808
ERROR: SPDD verification epoch 511, 000001b844f4e4c900ae0dfdc84a8845f71090b82fb473e6c70a31ee: ref 8286252067209 != comp 8286220721568
... (11 pools with stake mismatches totaling ~43.6 ADA)
```

### Missing SPO Rewards

```
ERROR: Missing rewards SPO: 9837e1eca79504f57acd4e12f2db93ee04a76bca308cae61a6ee205a 197 rewards
ERROR: Rewards verification: errors=1 epoch=510
```

## Fixes so far...

- [x] **Block count off by 2** (`9eb523ca`): Pass `total_blocks` from epoch activity message directly instead of recalculating from filtered SPO block counts
- [x] **Double treasury credit** (`9eb523ca`): Remove duplicate treasury addition for unregistered reward accounts (was being added both in payment loop and via `total_unpaid`)
- [x] **Shelley shared reward account bug** (`58cc11c0`): Only apply the Shelley-era bug workaround for `era < Allegra`
- [x] **Unregistered reward accounts** (`58cc11c0`): Track `registered` flag on rewards and route unregistered account rewards to treasury
- [x] **Failed Plutus tx handling** (`2af53e07`): Correct fee totals by handling collateral on failed transactions
- [x] **Pool owner reward account check** (`1f799bd1`): Add check for pool owner reward account registration
- [x] **Member rewards for non-owner reward accounts** (`cb62ccb5`): Include reward address rewards when delegator is not a pool owner
- [x] **DRep deregistration refunds** (`dfc365dc`): Refunds to deposits pot
- [x] **Governance proposal deposits** (`20677051`): Track governance action deposits/refunds correctly

## Remaining Issues

- [x] **SPDD stake mismatches (epoch 511)**: 11 pools still show stake differences totaling ~43.6 ADA
- [x] **Missing SPO rewards**: SPO `9837e1...` missing from calculation despite 197 expected rewards
- [x] **Deposits mismatch**: 100 ADA difference in deposits pot

## Testing Requirements

- Run `make run-bootstrap` and verify no `Verification mismatch` errors in logs
- SPDD verification should show 0 mismatches for all epochs
- Rewards verification should show 0 errors

## Definition of Done

- All verification checks pass from epoch 508 onwards
- No treasury/reserves/deposits mismatches
- No SPDD stake mismatches  
- No missing SPO rewards

### PR DESCRIPTION
**Pull request by lowhung**
### Rewards Calculation Fixes
- Remove deregistration check from rewards calculation - deregistration doesn't affect reward calculation, only how rewards are distributed (to the account if still registered, or to treasury if not). The bug was in the calculation step where we were incorrectly skipping the reward entirely rather than letting the distribution logic decide where it goes.
- Gate Shelley shared reward account bug to pre-Allegra eras only
- When pool reward account is a delegator (but not a pool owner), add their member rewards to leader rewards instead of losing them

### Governance Deposits Fix
- Don't track governance proposal deposits in `pots.deposits` - they are tracked separately in the governance state (`oblProposal` in the Cardano ledger), not in the UTxO state's `us_deposited` field. This was causing a 100k ADA mismatch per governance proposal.

### Retired SPO Rewards Fix
- Include retired SPOs in epoch snapshots for rewards calculation. When calculating rewards for epoch N, the system uses a "performance" snapshot (epoch N+1) to look up block counts. If a pool retired after producing blocks, it was missing from this snapshot, causing block count lookups to return 0 and rewards to be skipped.
- Changed `EpochSnapshot::new()` to iterate over the union of registered pools AND block-producing pools. Retired pools that produced blocks now get a minimal entry in the snapshot with their block count preserved.

### Block Count Fix
- Only pass Praos block counts in `spo_blocks` (excludes OBFT blocks from legacy nodes)

This uses work from #581 and #584 

## Related Issue(s)
Fixes #574

## How was this tested?
- mainnet full run
- unit tests didn't change

## Checklist
- [x] My code builds and passes local tests
- [ ] I added/updated tests for my changes, where applicable
- [ ] I updated documentation (if applicable)
- [x] CI is green for this PR

## Impact / Side effects
- Fixes SPDD verification mismatches for retired pools
- Fixes rewards verification errors for pools that retire after producing blocks
- Fixes deposits tracking for governance proposals

## Reviewer notes / Areas to focus

### CODE REVIEW

File: common/src/epoch_snapshot.rs [hunk 1]
```diff
@@ -91,19 +91,39 @@ impl EpochSnapshot {
...
+                    None => {
+                        // SPO wasn't in snapshot from 2 epochs ago (newly registered or retired).
+                        // Check if their CURRENT reward account is registered as a fallback.
+                        // Default to true if we can't verify - conservative approach to avoid
+                        // incorrectly denying legitimate rewards.
+                        if let Some(spo) = spo {
+                            stake_addresses
+                                .get(&spo.reward_account)
+                                .map(|sas| sas.registered)
+                                .unwrap_or(true)
```
Comment (sandtreader) [inline common/src/epoch_snapshot.rs]: Does this actually affect anything?  If so (and I've understood right) it implies an SPO's reward address was never registered or staked, but still they received rewards on it.  If so it calls into question the need to check for registration at all!

File: modules/accounts_state/src/rewards.rs [hunk 2]
```diff
@@ -145,8 +154,7 @@ pub fn calculate_rewards(
         // There was a bug in the original node from Shelley until Allegra where if multiple SPOs
         // shared a reward account, only one of them would get paid.
         // QUESTION: Which one?  Lowest hash seems to work in epoch 212
-        // TODO turn this off at Allegra start
-        if pay_to_pool_reward_account {
+        if pay_to_pool_reward_account && era < Era::Allegra {
```
Comment (sandtreader) [inline modules/accounts_state/src/rewards.rs]: Cool, glad it was that simple!

File: modules/tx_unpacker/src/tx_unpacker.rs [hunk 3]
```diff
@@ -67,15 +59,24 @@ impl TxUnpacker {
         publish_tx_validation_topic: Option<String>,
         // subscribers
         mut txs_sub: Box<dyn Subscription<Message>>,
-        mut bootstrapped_sub: Box<dyn Subscription<Message>>,
-        mut protocol_params_sub: Box<dyn Subscription<Message>>,
+        bootstrapped_sub: Option<Box<dyn Subscription<Message>>>,
```
[the remark this answers is not in the document]
Comment (lowhung) [reply modules/tx_unpacker/src/tx_unpacker.rs]: I cherry-picked those changes into this repo :) if/when you merge your architecture docs I can merge in main and resolve those conflicts.

File: common/src/stake_addresses.rs [hunk 4]
```diff
@@ -300,17 +300,18 @@ impl StakeAddressMap {
         sas_data
             .par_iter() // Rayon multi-threaded iterator
             .for_each(|(spo, (utxo_value, rewards))| {
+                let total_stake = *utxo_value + *rewards;
```
[the remark this answers is not in the document]
Comment (lowhung) [reply common/src/stake_addresses.rs]: We have opted to remove the `live` property all together, which was done in #581, sorry for the confusion around that!

File: common/src/stake_addresses.rs [hunk 5]
```diff
@@ -458,6 +459,34 @@ impl StakeAddressMap {
         }
     }
 
+    /// Deregister a DRep - clears all delegations to this DRep
+    ///
+    /// TODO: This currently iterates ALL stake addresses to find delegations (O(n)).
```
[the remark this answers is not in the document]
Comment (lowhung) [reply common/src/stake_addresses.rs]: Yep! Done here https://github.com/input-output-hk/acropolis/issues/588

File: common/src/epoch_snapshot.rs (hunk 1 above)
Comment (lowhung) [reply common/src/epoch_snapshot.rs]: Yeh this is not necessary / doesn't affect anything. I've unstaged it 👍🏻

File: modules/accounts_state/src/rewards.rs (hunk 2 above)
Comment (whankinsiv) [inline modules/accounts_state/src/rewards.rs]: These conditions should be nested so the else branch only logs in Shelley era.

**Review by whankinsiv — APPROVED** [review]
